#!/bin/bash
if [ $# -lt 3 ]; then
	printf "<language> <infile> <outfile>\n"
	exit 1
fi

SCORE_LANG=$1
shift
SCORE_FILE=$1
shift
SCORE_OUT=$1
shift

# stopword settings
STOP_PAT=$(pwd)/stop/stop
STOP_FORMAT=snowball

DIR_DATA=data
IDX=/data/clef/Clarity/work/fiz/index/$(echo $SCORE_LANG | tr '[:lower:]' '[:upper:]')

OUT=${SCORE_OUT}
IN=${SCORE_FILE}

OUT_DIR=$DIR_DATA/termDumpScoring-$(date +%Y-%m-%d+%H:%M:%S)
mkdir -p $OUT_DIR

OUT=$OUT_DIR/$OUT

CLASS=de.unihildesheim.iw.fiz.cli.ScoreTopicPassages
ARGS="-i ${IN} -o ${OUT} -idx ${IDX} -stop ${STOP_PAT} -stop-format ${STOP_FORMAT} -lang ${SCORE_LANG} -ct-threshold 0.01 "

echo mvn exec:java -Dmaven.repo.local=/home/bertra/.m2/repository -Dexec.mainClass=${CLASS} -Dexec.args="${ARGS} $*" 
#> ${OUT_DIR}/log.txt
