#!/bin/bash
. "$(dirname $0)/mvn.inc.sh"

if [ $# -lt 3 ]; then
	printf "<language> <test|train> <suffix>\n"
	exit 1
fi

SCORE_LANG=$1
shift
SCORE_TYPE=$1
shift
SCORE_SUFFIX=$1
shift

# stopword settings
STOP_PAT=$(pwd)/stop/stop
STOP_FORMAT=snowball

DIR_DATA=data/clef-topics
IDX=/data/clef/Clarity/work/fiz/index/$(echo $SCORE_LANG | tr '[:lower:]' '[:upper:]')

if [ "$SCORE_TYPE" == "test" ]; then
	OUT=topics-clef-test-${SCORE_SUFFIX}-${SCORE_LANG}.xml
	IN=topics-test.xml
elif [ "$SCORE_TYPE" == "train" ]; then
	OUT=topics-clef-train-${SCORE_SUFFIX}-${SCORE_LANG}.xml
	IN=topics-train.xml
else
	printf "Unknown passage group '$1'.\n"
fi

IN=$DIR_DATA/$IN
OUT=$DIR_DATA/$OUT

CLASS=de.unihildesheim.iw.clef.cli.ScoreTopicPassages
ARGS="-i ${IN} -o ${OUT} -idx ${IDX} -stop ${STOP_PAT} -stop-format ${STOP_FORMAT} -data ${DIR_DATA} -only-lang ${SCORE_LANG} -fields-no-suffix"

${MVN_CMD} -Dexec.mainClass="${CLASS}" -Dexec.args="${ARGS} $*"
