#!/bin/bash
. "$(dirname $0)/mvn.inc.sh"

if [ $# -eq 0 ]; then
	printf "You need to specify 'test' or 'train' for passage extraction.\n"
	exit 1
fi

DIR_DATA_BASE=/data/clef/source-data
OUT_PREFIX=topics

if [ "$1" == "test" ]; then
	DIR_DATA=$DIR_DATA_BASE/clef-ip-2012-PSG-test-topics
	FILE_TOPICS=clefip-2012-clms-psg-topics.txt
	OUT=${OUT_PREFIX}-test.xml
elif [ "$1" == "train" ]; then
	DIR_DATA=$DIR_DATA_BASE/training-corrected
	FILE_TOPICS=topics.txt
	OUT=${OUT_PREFIX}-train.xml
else
	printf "Unknown passage group '$1'.\n"
fi

OUT_DIR=data/clef-topics
mkdir -p $OUT_DIR
OUT=$OUT_DIR/$OUT

CLASS=de.unihildesheim.iw.clef.cli.ExtractTopicPassages
ARGS="-data $DIR_DATA -topicfile $FILE_TOPICS -out $OUT"

${MVN_CMD} -Dexec.mainClass="${CLASS}" -Dexec.args="${ARGS}"
