#!/bin/bash

if [ $# -lt 1 ]; then
	printf "<DATAPATH>\n"
	exit 1
fi

DATAPATH=$1
shift

#LANGUAGES=( "de" "en" "fr" )
LANGUAGES=( "de" )
#FIELDS=( "claims" "detd" )
FIELDS=( "claims" )
#SCORERS=( "dcs" "ics" "scs" )
SCORERS=( "dcs" )
#SAMPLES=( 1 2 3 )
SAMPLES=( 1 )

csv2xml() {
	for i in "${LANGUAGES[@]}"; do
		echo "Converting CSV to scoring-XML (${i})"
		for j in "${SAMPLES[@]}"; do
			echo "Sample ${j}"
			LNG=${i}
			SMP=${j}
			./exec_Csv2Xml -csvfile ${DATAPATH}/df-term-bins-${LNG}_sample-${SMP}.csv -out ${DATAPATH}/df-term-bins-${LNG}_sample-${SMP}.xml -lang ${LNG}
		done
	done
}

term2sentence() {
	for i in "${LANGUAGES[@]}"; do
		echo "Collection sentences for terms (${i})"
		for j in "${SAMPLES[@]}"; do
			echo "Sample ${j}"
			LNG=${i}
			SMP=${j}
			./exec_SentenceExtractor ${LNG} ${DATAPATH}/df-term-bins-${LNG}_sample-${SMP}.xml ${DATAPATH}/df-term-bins-sentences-${LNG}_sample-${SMP}.xml
		done
	done
}

score() {
	for i in "${LANGUAGES[@]}"; do
		echo "Scoring (${i})"
		for j in "${SAMPLES[@]}"; do
		echo "Sample ${j}"
			for k in "${FIELDS[@]}"; do
				echo "Field ${k}"
				for m in "${SCORERS[@]}"; do
					echo "Scorer ${m}"
					LNG=${i}
					SMP=${j}
					FLD=${k}
					SCR=${m}
					echo "..terms"
					./exec_TermDumpScoring ${LNG} ${DATAPATH}/df-term-bins-${LNG}_sample-${SMP}.xml df-term-bins-${LNG}_sample-${SMP}.xml -scorer ${SCR} -fields ${FLD}
					echo "..sentences"
					./exec_TermDumpScoring ${LNG} ${DATAPATH}/df-term-bins-sentences-${LNG}_sample-${SMP}.xml df-term-bins-sentences-${LNG}_sample-${SMP}.xml -scorer ${SCR} -fields ${FLD}
				done
			done
		done
	done
}

#csv2xml
#term2sentence
score
