#!/bin/bash
# Dump term-data (term & document frequency) for a specific language and field.
# An individual dump will be created for each IPC-Section (A-H).
#
# ./exec_DumpTermDataByIPCSection <LANGUAGE-CODE> <LUCENE-FIELD>

if [ $# -lt 2 ]; then
	printf "<language> <field>\n"
	exit 1
fi

DMPLANG=$1
shift
DMPFLD=$1
shift

IPC_SECS=( "A" "B" "C" "D" "E" "F" "G" "H" )

dump() {
  IPC=$1
  IPC_UC=$(echo $IPC | tr '[:lower:]' '[:upper:]')
  IPC_LC=$(echo $IPC | tr '[:upper:]' '[:lower:]')
  ./exec_DumpTermData ${DMPLANG} -dbfile data/termDump-${DMPLANG}-${DMPFLD}-ipc_${IPC_LC}.sqlite -field ${DMPFLD} -ipc ${IPC_UC} | tee data/termDump-${DMPLANG}-${DMPFLD}-ipc_${IPC_LC}.log
}

for IPC in "${IPC_SECS[@]}"; do
  dump ${IPC}
done;
