#!/bin/sh
. "$(dirname $0)/mvn.inc.sh"

TARGET=/data/clef/Clarity/work/fiz/index
mkdir -p $TARGET

# stopword settings
STOP_PAT=$(pwd)/stop/stop
STOP_FORMAT=snowball

CLASS=de.unihildesheim.iw.fiz.cli.BuildIndex
ARGS="-data $TARGET -stop $STOP_PAT -stop-format $STOP_FORMAT"

${MVN_CMD} -Dexec.mainClass="${CLASS}" -Dexec.args="${ARGS} $*"


