#!/bin/sh
if [ $# -lt 1 ]; then
	printf "<setup>:\n"
	printf " - clefBaseline\n"
	printf " - clefCommonTerms\n"
	exit 1
fi

case "$1" in
	"clefBaseline")
		./exec_ClefScoring de test baseline -fields "detd" -prefix baseline -scorer dcs > score-de-detd-baseline.log
		;;
	"clefCommonTerms")
		./exec_ClefScoring de test commonterms-dcs -fields "detd" -prefix commonterms -conf common-terms -scorer dcs > score-de-detd-commonterms-dcs.log
		#./exec_ClefScoring de test commonterms-ics -fields "detd" -prefix commonterms -conf common-terms -scorer ics
		#./exec_ClefScoring de test commonterms-scs -fields "detd" -prefix commonterms -conf common-terms -scorer scs
		;;
	*)
		printf "Unknown setup.\n"
	;;
esac


