#!/bin/bash
. "$(dirname $0)/mvn.inc.sh"

if [ $# -lt 2 ]; then
	printf "<language> <suffix>\n"
	exit 1
fi

SCORE_LANG=$1
shift
SUFFIX=$1
shift

# stopword settings
STOP_PAT=$(pwd)/stop/stop
STOP_FORMAT=snowball

DIR_DATA=data/termDump
IDX=/data/clef/Clarity/work/fiz/index/$(echo $SCORE_LANG | tr '[:lower:]' '[:upper:]')

OUT=$DIR_DATA/common-terms-${SCORE_LANG}-${SUFFIX}.csv

CLASS=de.unihildesheim.iw.cli.DumpCommonTerms
ARGS="-o ${OUT} -idx ${IDX} -stop ${STOP_PAT} -stop-format ${STOP_FORMAT} -data ${DIR_DATA} -lang ${SCORE_LANG} -prefix ${SUFFIX}"

${MVN_CMD} -Dexec.mainClass="${CLASS}" -Dexec.args="${ARGS} $*"
