#!/bin/sh

prepare() {
	echo "Converting CSV to scoring-XML"
	./exec_Csv2Xml -csvfile data/df-term-bins_sample-1.csv -out data/df-term-bins_sample-1.xml -lang de
	./exec_Csv2Xml -csvfile data/df-term-bins_sample-2.csv -out data/df-term-bins_sample-2.xml -lang de
	./exec_Csv2Xml -csvfile data/df-term-bins_sample-3.csv -out data/df-term-bins_sample-3.xml -lang de
}
prepare_sent() {
	echo "Retrieving sentences for scoring-XML"
	./exec_SentenceExtractor de data/df-term-bins_sample-1.xml data/df-term-bins-sentences_sample-1.xml
	./exec_SentenceExtractor de data/df-term-bins_sample-2.xml data/df-term-bins-sentences_sample-2.xml
	./exec_SentenceExtractor de data/df-term-bins_sample-3.xml data/df-term-bins-sentences_sample-3.xml
}

score() {
	SMP=$1
	SCR=$2
	FLD=$3
	echo "== Score terms -- smp:${SMP} scr:${SCR} fld:${FLD}"
	./exec_TermDumpScoring de data/df-term-bins_sample-${SMP}.xml df-term-bins_sample-${SMP}.xml -scorer ${SCR} -fields ${FLD}
}

score_sent() {
	SMP=$1
	SCR=$2
	FLD=$3
	echo "== Score sentences -- smp:${SMP} scr:${SCR} fld:${FLD}"
	./exec_TermDumpScoring de data/df-term-bins-sentences_sample-${SMP}.xml df-term-bins-sentences_sample-${SMP}.xml -scorer ${SCR} -fields ${FLD}
}

scoreSample() {
	score ${1} scs claims
	score ${1} scs detd
	score ${1} dcs claims
	score ${1} dcs detd
	score ${1} ics claims
	score ${1} ics detd
}

scoreSample_sent() {
	score_sent ${1} scs claims
	score_sent ${1} scs detd
	score_sent ${1} dcs claims
	score_sent ${1} dcs detd
	score_sent ${1} ics claims
	score_sent ${1} ics detd
}

scoreSamples() {
	scoreSample 1
	scoreSample 2
	scoreSample 3
}

scoreSamples_sent() {
	scoreSample_sent 1
	scoreSample_sent 2
	scoreSample_sent 3
}

#prepare
#prepare_sent

#scoreSamples
#scoreSamples_sent

score 2 scs claims
score 2 scs detd
score 3 scs claims
score 3 scs detd

