#!/bin/sh

# LUCENE 5212 5158
# JDK 8024830

echo Query: $1
# memory setting
JVM="-Xms128m -Xmx2G"
MAVEN_OPTS="$MAVEN_OPTS $JVM"

mvn exec:java -Dexec.mainClass="de.unihildesheim.lucene.index.IndexInfo" -Dexec.args="-index ./data/index $*"
