#!/bin/bash

# memory setting
JVM_MEM="-Xms128m -Xmx2G"
JVM_DEFAULT="-server -d64"

JVM="$JVM_DEFAULT $JVM_MEM"
MAVEN_OPTS="$MAVEN_OPTS $JVM"

HOST=$(hostname)

TMP=/data/clef/tmp
RUNTMP="-Djava.io.tmpdir=${TMP}"

rm -rf ${TMP}/mapdb-temp*
rm -rf ${TMP}/idx*

if [ $# -eq 0 ]; then
  	mvn $RUNTMP test
else
	mvn $RUNTMP -Dtest="$*" test
fi

