#!/bin/bash

# memory setting
JVM_MEM="-Xms128m -Xmx2G"
JVM_DEFAULT="-server -d64" # -d64 -ea

JVM="$JVM_DEFAULT $JVM_MEM"
MAVEN_OPTS="$MAVEN_OPTS $JVM"

HOST=$(hostname)

if [ "$HOST" == "bigBhoerdzn" ]; then
	RUNTMP="-Djava.io.tmpdir=/media/Brain2/tmp"
else
	RUNTMP="-Djava.io.tmpdir=/home/bertra/CLEF/test/tmp"
fi

rm -rf ../tmp/mapdb-tmp*
rm -rf ../tmp/idx*

if [ $# -eq 0 ]; then
  	mvn $RUNTMP test
else
	mvn $RUNTMP -Dtest="$*" test
fi

