#!/bin/sh
TARGET=/data/clef/Clarity/work/fiz/index
mkdir -p $TARGET

# stopword settings
STOP_PAT=$(pwd)/stop/stop
STOP_FORMAT=snowball

CLASS=cli.BuildIndex
ARGS="-data $TARGET -stop $STOP_PAT -stop-format $STOP_FORMAT"

./run ${CLASS} ${ARGS} $*
