#!/bin/bash
source $(dirname $0)/data.conf.inc
source $(dirname $0)/misc.inc
PWD=$(pwd)
TARGET=${PWD}/data

# check if data is there
if [ ! -d "$TARGET" ]; then
  echo "Data directory ${TARGET} does not exists."
	exit 1
fi

DTDOld="http://www.ir-facility.org/dtds/patents/v1.4/patent-document.dtd"
DTDNew="file://${TMP_DATA}/dtd/patent-document.dtd"

echo Replacing ${DTDOld} with ${DTDNew} in all XML files in ${TARGET}
confirm || exit 0

echo Directory ${TARGET}/EP..
if confirm; then
	cd "${TARGET}/EP"
	find . -type f -name "*.xml" -print0 | xargs -0 sed -i "s#${DTDOld}#${DTDNew}#g"
	cd "${PWD}"
fi

echo Directory ${TARGET}/WO..
if confirm; then
	cd "${TARGET}/WO"
	find . -type f -name "*.xml" -print0 | xargs -0 sed -i "s#${DTDOld}#${DTDNew}#g"
	cd "${PWD}"
fi
