#!/bin/bash
source $(dirname $0)/solr.conf.inc
source $(dirname $0)/data.conf.inc

echo Starting Solr in background. Navigato to http://localhost:${SOLR_PORT}/solr/ for access.
echo java: ${JAVA}
echo path: ${SOLR_PATH}
echo control port: ${SOLR_CONTROL_PORT}
echo home: ${SOLR_HOME}
echo temp data: ${TMP_DATA}

# store source dir
PWD=$(pwd)

# change to solr dir
cd "solr/${SOLR_PATH}/example"

# java and solr options set by solr.conf.inc
${JAVA} -server -cp "./clef" -DSTOP.KEY=solrcontrol -DSTOP.PORT=${SOLR_CONTROL_PORT} -Dsolr.solr.home=${SOLR_HOME} -Xms${XMS} -Xmx${XMX} -jar start.jar $1 

# back to source dir
cd "${PWD}"
